a = input('digite algo:')
print('Qual é seu tipo?', type(a))
print('Ele é alfa numerico ?', a.isalpha())
print('Ele é minusculo ?', a.islower())
print('Ele é decimal ?', a.isdecimal())
print('Ele tem espaço ?', a.isspace())
