n= str(input('digite seu nome inteiro:'))
nmaiusculo = n.upper()
print(f'Seu nome em maiusculas é \033[35m{nmaiusculo}\033[m')
nminusculo = n.lower()
print(f'seu nome em minusculas é \033[4;31m{nminusculo}\033[m')
nquantidade = len(n)
print(f'seu nome tem ao todo \033[1;32m{nquantidade}\033[m letras')
n1quantidade = n.split()
print(f'seu primeiro nome tem \033[7;34m{len(n1quantidade[0])}\033[m')
